language: python
sudo: required
dist: xenial
python:
     - "2.7"
install:
     - pip install -r pip_dependencies
     - sudo pip install -r pip_dependencies
     - sudo -H ./setup
script: nosetests -vv --nocapture 
